buildscript {
	ext {
		cleanArchitectureVersion = '3.22.1'
		springBootVersion = '3.4.4'
        lombokVersion = '1.18.38'
	}
}

plugins {
	id 'co.com.bancolombia.cleanArchitecture' version "${cleanArchitectureVersion}"
	id 'org.springframework.boot' version "${springBootVersion}" apply false
}

apply from: './main.gradle'